/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as ListIndexRouteImport } from './routes/list/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatIdIndexRouteImport } from './routes/chat/$id/index'
import { Route as ChatIdSettlementIndexRouteImport } from './routes/chat/$id/settlement/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListIndexRoute = ListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdIndexRoute = ChatIdIndexRouteImport.update({
  id: '/chat/$id/',
  path: '/chat/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdSettlementIndexRoute = ChatIdSettlementIndexRouteImport.update({
  id: '/chat/$id/settlement/',
  path: '/chat/$id/settlement/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatIndexRoute
  '/home': typeof HomeIndexRoute
  '/list': typeof ListIndexRoute
  '/user': typeof UserIndexRoute
  '/chat/$id': typeof ChatIdIndexRoute
  '/chat/$id/settlement': typeof ChatIdSettlementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatIndexRoute
  '/home': typeof HomeIndexRoute
  '/list': typeof ListIndexRoute
  '/user': typeof UserIndexRoute
  '/chat/$id': typeof ChatIdIndexRoute
  '/chat/$id/settlement': typeof ChatIdSettlementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat/': typeof ChatIndexRoute
  '/home/': typeof HomeIndexRoute
  '/list/': typeof ListIndexRoute
  '/user/': typeof UserIndexRoute
  '/chat/$id/': typeof ChatIdIndexRoute
  '/chat/$id/settlement/': typeof ChatIdSettlementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/home'
    | '/list'
    | '/user'
    | '/chat/$id'
    | '/chat/$id/settlement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/home'
    | '/list'
    | '/user'
    | '/chat/$id'
    | '/chat/$id/settlement'
  id:
    | '__root__'
    | '/'
    | '/chat/'
    | '/home/'
    | '/list/'
    | '/user/'
    | '/chat/$id/'
    | '/chat/$id/settlement/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ListIndexRoute: typeof ListIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  ChatIdIndexRoute: typeof ChatIdIndexRoute
  ChatIdSettlementIndexRoute: typeof ChatIdSettlementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/': {
      id: '/list/'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id/': {
      id: '/chat/$id/'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id/settlement/': {
      id: '/chat/$id/settlement/'
      path: '/chat/$id/settlement'
      fullPath: '/chat/$id/settlement'
      preLoaderRoute: typeof ChatIdSettlementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  ListIndexRoute: ListIndexRoute,
  UserIndexRoute: UserIndexRoute,
  ChatIdIndexRoute: ChatIdIndexRoute,
  ChatIdSettlementIndexRoute: ChatIdSettlementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
